# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1507634846);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1507634966);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1507690868);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1507634690);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1507656170);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1507635086);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.lastDir", "/home/arya/Downloads/Wallpapers");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1507634326);
user_pref("browser.laterrun.bookkeeping.sessionCount", 8);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 37);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1507690762040");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1507692450040");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1507690763402");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1507694363402");
user_pref("browser.search.countryCode", "IN");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160606113944");
user_pref("browser.slowStartup.averageTime", 4501);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20160606113944");
user_pref("browser.startup.homepage_override.mstone", "47.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":1}");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"loop-button\",\"pocket-button\"]},\"seen\":[\"loop-button\",\"pocket-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"PanelUI-contents\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1507634390163");
user_pref("datareporting.sessions.current.activeTicks", 6);
user_pref("datareporting.sessions.current.firstPaint", 2835);
user_pref("datareporting.sessions.current.main", 71);
user_pref("datareporting.sessions.current.sessionRestored", 2987);
user_pref("datareporting.sessions.current.startTime", "1507692350700");
user_pref("datareporting.sessions.current.totalTime", 28);
user_pref("datareporting.sessions.currentIndex", 7);
user_pref("datareporting.sessions.previous.0", "{\"s\":1507634321645,\"a\":1,\"t\":126,\"c\":true,\"m\":783,\"fp\":8748,\"sr\":8505}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1507634449305,\"a\":23,\"t\":274,\"c\":true,\"m\":80,\"fp\":4034,\"sr\":3655}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1507634725187,\"a\":922,\"t\":20982,\"c\":true,\"m\":71,\"fp\":2877,\"sr\":3048}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1507655718364,\"a\":4,\"t\":58,\"c\":true,\"m\":81,\"fp\":3880,\"sr\":3523}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1507655790701,\"a\":74,\"t\":526,\"c\":true,\"m\":80,\"fp\":3890,\"sr\":3561}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1507690744021,\"a\":219,\"t\":1457,\"c\":true,\"m\":1279,\"fp\":8713,\"sr\":9306}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1507692296646,\"a\":4,\"t\":53,\"c\":true,\"m\":71,\"fp\":2759,\"sr\":2914}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("e10s.rollout.cohort", "unsupportedChannel");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.3.2\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"e10srollout@mozilla.org\":{\"version\":\"1.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"firefox@getpocket.com\":{\"version\":\"1.0.2\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"47.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"47.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:47.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1507634850);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20170302.01");
user_pref("extensions.lastAppVersion", "47.0");
user_pref("extensions.lastPlatformVersion", "47.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.3.2\",\"st\":1465217168000},\"e10srollout@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"e\":true,\"v\":\"1.0\",\"st\":1465217167000},\"firefox@getpocket.com\":{\"d\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"e\":true,\"v\":\"1.0.2\",\"st\":1465217168000}},\"app-global\":{\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"47.0\",\"st\":1465217639000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"47.0\",\"st\":1465217167000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"47.0\",\"st\":1465217641000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.2\",\"st\":1442597402000}}}");
user_pref("gecko.buildID", "20160606113944");
user_pref("gecko.mstone", "47.0");
user_pref("idle.lastDailyNotification", 1507635183);
user_pref("loop.copy.ticket", 21);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1507634394);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20160606113944");
user_pref("media.gmp-manager.lastCheck", 1507634391);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1507635184);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1507635184);
user_pref("toolkit.startup.last_success", 1507692350);
user_pref("toolkit.telemetry.cachedClientID", "9c8bcfe8-aec7-4947-a2bd-6cc1ef1b205c");
user_pref("toolkit.telemetry.previousBuildID", "20160606113944");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
